name: Go Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install frontend dependencies
      run: npm i
      working-directory: ./web

    - name: Build frontend
      run: npm run build
      working-directory: ./web

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o mirror.exe ./cmd/mirror

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o mirror ./cmd/mirror

    - name: Package Windows Artifact
      run: zip -r mirror-windows.zip mirror.exe config.json web/dist

    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: mirror-windows-package
        path: mirror-windows.zip

    - name: Package Linux Artifact
      run: tar -czvf mirror-linux.tar.gz mirror config.json web/dist

    - name: Upload Linux Package
      uses: actions/upload-artifact@v4
      with:
        name: mirror-linux-package
        path: mirror-linux.tar.gz
